name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  test-cli-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CLI unit tests
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            cd cli
            npm run test
  test-web-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run web unit tests
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            cd web
            npm run test:unit
  test-web-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run web integration tests
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            cd web
            sudo npx playwright install-deps
            npx playwright install
            npm run test:integration
  lint-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint web
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            cd web
            npm run lint
  svelte-check-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run svelte-check
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            cd web
            npm run check
